/**
 * the base mining class for the master
 */

#pragma once

#include "CLMap.h"
#include "Pattern.h"

class Miner {
private:
    CLMap processed;

protected:
    //expected patterns generated by an approximate miner. These patterns follow the same as the exact ones.
    //it is used to have more candidates when there are not enough candidates to make workers busy.
    std::vector<CLMap *> *expected_frequent_patterns = 0;
    std::vector<CLMap *> *expected_infrequent_patterns = 0;
    std::map<int, std::map<int, std::set<int>>> frequent_patterns_domain;
    std::vector<Pattern *> frequent_pattern_vec;

    GraphX *graph = 0;
    int support;
    //frequent edges
    CLMap frequent_edges;
    std::map<std::string, std::map<int, std::set<int>>> freq_pattern_pairs;
    std::map<int, std::set<int>> freq_edge_pairs;
    std::map<std::string, long long> is_freqtimes;
    std::set<std::string> cl_set;

    //frequent patterns sorted in a vector, nth element in the vector is hash map of all patterns having n edges
    //each hashmap is keyed by the canonical form of the value graph (pattern)
    std::vector<CLMap *> frequent_patterns;
    std::vector<CLMap *> infrequent_patterns;
    std::vector<CLMap *> candidates;
    std::map<int, Pattern *> currently_checking;

    void print(std::vector<CLMap *> &);
    void remove_pattern(Pattern *pattern, std::vector<CLMap *> &data);

public:
    static int num_is_freq_calls;
    static int num_freqs;
    static int num_infreq;

    Miner();

    ~Miner();

    void init_mining(std::string, int, int, int);

    void start_mining(int);

    void load_graph(std::string base_name, int graph_type, int support, CLMap &freq_edges);

    void load_graph_with_pairs(std::string base_name, int graph_type, int support, CLMap &freq_edges, int seed_node_id);

    void print_result();

    void print_candidates();

    int get_support() { return support; }

    void set_support(int support) { this->support = support; }

    CLMap &get_frequent_edges() { return frequent_edges; }

    void set_frequent_edges(CLMap &freqEdges);

    void extend_freq_edges();

    std::vector<CLMap *> *get_frequent_patterns() { return &frequent_patterns; }

    std::vector<CLMap *> *get_infrequent_patterns() { return &infrequent_patterns; }

    void set_expected_patterns(std::vector<CLMap *> *ex_freq_patt, std::vector<CLMap *> *ex_infreq_patt) {
        expected_frequent_patterns = ex_freq_patt;
        expected_frequent_patterns->at(1)->clear();
        expected_infrequent_patterns = ex_infreq_patt;
    }
};

